# Setting up Data

In [537]:
#Importing necessary packages

import pandas as pd
import numpy as np 
import numpy.linalg as la

In [538]:
#Importing and setting up data

family = pd.read_csv('famb.data', delim_whitespace=True, header=None, index_col=0) # Load data
family = family.rename(columns={1: 'Mom_educ', 2: 'Dad_educ', 3: 'Num_siblings', 4: 'Urban', 5:'Nuclear', 6:'Family_income', 7:'South', 8:'AFQT_score'}) # Name columns
family = family.replace(-9999, np.nan) # Replacing NaN values
column_values = family['Family_income'].values # storing values as a numpy array

In [539]:
# Print min and max values for each variable.

for column in family.columns:
    # Find the minimum value of the column
    min_value = family[column].min()

    # Find the maximum value of the column
    max_value = family[column].max()

    print(column)
    print("Minimum value:", min_value)
    print("Maximum value:", max_value)
    print('-----------------')

Mom_educ
Minimum value: 0
Maximum value: 20
-----------------
Dad_educ
Minimum value: 0
Maximum value: 20
-----------------
Num_siblings
Minimum value: 0
Maximum value: 15
-----------------
Urban
Minimum value: 0
Maximum value: 1
-----------------
Nuclear
Minimum value: 0
Maximum value: 1
-----------------
Family_income
Minimum value: 0.0
Maximum value: 150347.1
-----------------
South
Minimum value: 0
Maximum value: 1
-----------------
AFQT_score
Minimum value: 1
Maximum value: 99
-----------------


In [540]:
# Loading and setting up education data for the schooling variable.

edu = pd.read_csv('ed.data', delim_whitespace=True, header=None, index_col=0) # Loading education data
new_column_names = [str(year) for year in range(1979, 1991)] 
edu.columns = new_column_names # Rename the columns
edu = edu.replace(-9999, np.nan) # Define the NaN values
edu.index.name = 'id' # creating id column
panel_edu = edu.reset_index().melt(id_vars='id', var_name='Year', value_name='Education') # Reformatting data

shifted_edu = edu.shift(-1,axis=1) # Create shiftet data set for dummy variable
dummy_school = shifted_edu -edu # Create dummy for attending school for an additional year.
dummy_school = dummy_school.drop(['1990','1979'], axis=1) # Dropping year 1979 and 1990
dummy_school.index.name = 'id' # Create id column
panel_dummy_school = dummy_school.reset_index().melt(id_vars='id', var_name ='Year', value_name='Dummy_school') #Reformatting data

edu_going_in = edu.shift(1, axis=1) # shift so that the value in 1980 is the value from 1979
edu_going_in = edu.drop(['1990','1979'], axis=1) # Dropping year 1979 and 1990
edu_going_in.index.name = 'id' # Creating id column
panel_edu_going_in = edu_going_in.reset_index().melt(id_vars='id', var_name='Year', value_name='Education_going_in') # Reformatting data
panel_edu = panel_edu.drop(columns='id') # Creating id column


In [541]:
# Find the minimum value of the DataFrame excluding the first column
min_value = edu.iloc[:, 1:].values.min()

# Find the maximum value of the DataFrame excluding the first column
max_value = edu.iloc[:, 1:].values.max()

print("Minimum value of the DataFrame (excluding the identifier column):", min_value)
print("Maximum value of the DataFrame (excluding the identifier column):", max_value)

Minimum value of the DataFrame (excluding the identifier column): 6
Maximum value of the DataFrame (excluding the identifier column): 20


In [542]:
# Reading the experience data set and setting it up

exp = pd.read_csv('exp.data', delim_whitespace=True, header=None, index_col=0)
exp.columns = new_column_names
exp = exp.replace(-9999, np.nan)
exp.index.name = 'id'
panel_exp = exp.reset_index().melt(id_vars='id', var_name='Year', value_name='Experience') # Reformatting into classic panel data form

diff_exp = exp.diff(axis=1) #Calculating difference in experience
dummy_work = (diff_exp > 0).astype(int) #Creating dummy for working
dummy_work = dummy_work.drop(['1979','1990'], axis=1) # Dropping year 1979 and 1990
dummy_work.index.name = 'id' # Creating id column
panel_dummy_work = dummy_work.reset_index().melt(id_vars='id', var_name ='Year', value_name='Dummy_work') #Reformatting 

exp_going_in = exp.shift(1, axis=1) # Shift axis in experience data set
exp_going_in = exp_going_in.drop(['1990','1979'], axis=1) # Dropping year 1979 and 1990
exp_going_in.index.name = 'id' # Creating id column
panel_exp_going_in = exp_going_in.reset_index().melt(id_vars='id', var_name='Year', value_name='Experience_going_in') # Reformatting data set


In [543]:
# Creating interruption dummy
dummy_interrup = ((dummy_school == 0) & (dummy_work == 0)).astype(int)
dummy_interrup.index.name = 'id' # Creating id column
panel_dummy_interrup = dummy_interrup.reset_index().melt(id_vars='id', var_name ='Year', value_name='Dummy_interrup') # Reformatting data

In [544]:
#Experience
# Find the minimum value of the DataFrame excluding NaN values and the first column
min_value = np.nanmin(exp.iloc[:, 1:].values)

# Find the maximum value of the DataFrame excluding NaN values and the first column
max_value = np.nanmax(exp.iloc[:, 1:].values)

print("Minimum value of the DataFrame (excluding NaN values and the identifier column):", min_value)
print("Maximum value of the DataFrame (excluding NaN values and the identifier column):", max_value)

Minimum value of the DataFrame (excluding NaN values and the identifier column): 0.0
Maximum value of the DataFrame (excluding NaN values and the identifier column): 16.94


In [545]:
# Loading and setting up data for wage

wage = pd.read_csv('wage.data', delim_whitespace=True, header=None, index_col=0) # Loading data
wage.columns = new_column_names # Column names
wage = wage.replace(-9999, np.nan) # Defining NaN values
wage = wage.drop(['1979','1990'], axis=1) # Dropping year 1979 and 1990
wage.index.name = 'id' # Creating id column
panel_wage = wage.reset_index().melt(id_vars='id', var_name='Year', value_name='Wage') # Reformatting data

In [546]:
# Find the minimum value of the DataFrame excluding NaN values and the first column
min_value = np.nanmin(wage.iloc[:, 1:].values)

# Find the maximum value of the DataFrame excluding NaN values and the first column
max_value = np.nanmax(wage.iloc[:, 1:].values)

print("Minimum value of the DataFrame (excluding NaN values and the identifier column):", min_value)
print("Maximum value of the DataFrame (excluding NaN values and the identifier column):", max_value)

Minimum value of the DataFrame (excluding NaN values and the identifier column): 2.01
Maximum value of the DataFrame (excluding NaN values and the identifier column): 36.82


In [547]:
# Merging variables into one data set
merged_df = pd.merge(panel_dummy_school, panel_edu_going_in, on = ['id','Year'])
merged_df = pd.merge(merged_df, panel_dummy_interrup, on = ['id','Year'])
merged_df = pd.merge(merged_df, panel_dummy_work, on = ['id','Year'])
merged_df = pd.merge(merged_df, panel_exp_going_in, on = ['id','Year'])
merged_df = pd.merge(merged_df, panel_wage, on = ['id','Year'])
merged_df.to_csv('merged_data.data', sep='\t', index=False) # Export DataFrame to a .data file

# Estimating OLS

In [548]:
# Laver OLS estimation
dat = family.copy()
dat['constant'] = np.ones(family.shape[0])
dat['Family_income'] = dat['Family_income'] / 1000
# Estimerer model (1)
#For at få det rigtige intercept, trækker vi 6 fra y-værdien = highest grade completed, fordi stort set alle individer har gået 6 år i skole.
y = edu[edu.columns[-1]].values-6
X_m1 = dat[['constant','Dad_educ','Mom_educ']].values

# Print model (1)
betahat_m1 = np.linalg.inv(X_m1.T @ X_m1) @ X_m1.T @ y
print(betahat_m1.round(4))

#Print model (2)
X_m2 = dat[['constant','Dad_educ','Mom_educ','Family_income']].values
betahat_m2 = np.linalg.inv(X_m2.T @ X_m2) @ X_m2.T @ y
print(betahat_m2.round(4))

#Print model (3)
X_m3 = dat[['constant','Dad_educ','Mom_educ','Family_income','Num_siblings']].values
betahat_m3 = np.linalg.inv(X_m3.T @ X_m3) @ X_m3.T @ y
print(betahat_m3.round(4))

#Print model (4)
X_m4 = dat[['constant','Dad_educ','Mom_educ','Family_income','Num_siblings','Nuclear','Urban','South']].values
betahat_m4 = np.linalg.inv(X_m4.T @ X_m4) @ X_m4.T @ y
print(betahat_m4.round(5))

[1.15   0.2565 0.2279]
[1.307  0.22   0.1948 0.0178]
[ 2.116   0.2073  0.1776  0.0173 -0.1391]
[ 2.10043  0.20726  0.1683   0.01545 -0.14545  0.43123 -0.04957 -0.34782]


In [549]:
# Calculate residuals
res_OLS_m1 = y - X_m1@betahat_m1

# Estimate variance
K_m1 = X_m1.shape[1]
N_m1 = X_m1.shape[0]
SSR_m1 = res_OLS_m1.T@res_OLS_m1
print(SSR_m1)
sigma2_OLS_m1 = SSR_m1/(N_m1-K_m1)
var_m1 = sigma2_OLS_m1*la.inv(X_m1.T@X_m1)

# Calculate standard errors
se_m1 = np.sqrt(np.diag(var_m1)).reshape(-1,1)

# Display standard error
print("se_OLS_m1 = ",se_m1.round(2))
print(np.sqrt(var_m1.diagonal()), betahat_m1)


8470.728866248894
se_OLS_m1 =  [[0.26]
 [0.02]
 [0.03]]
[0.26393335 0.01933999 0.02729107] [1.15002725 0.25646102 0.22794135]


In [550]:
Ainv = la.inv(X_m1.T@X_m1)
u2 = res_OLS_m1 ** 2
xTu2 = X_m1.T * u2 
cov = Ainv @ (xTu2 @ X_m1) @ Ainv
se = np.sqrt(np.diag(cov))
np.diag(cov)

array([0.08159917, 0.00043539, 0.00089316])

In [551]:
# Calculate residuals
res_OLS_m2 = y - X_m2@betahat_m2

# Estimate variance
K_m2 = X_m2.shape[1]
N_m2 = X_m2.shape[0]
SSR_m2 = res_OLS_m2.T@res_OLS_m2
sigma2_OLS_m2 = (np.array(SSR_m2/(N_m2-K_m2)))
var_m2 = sigma2_OLS_m2*la.inv(X_m2.T@X_m2)

# Calculate standard errors
se_m2 = np.sqrt(var_m2.diagonal()).reshape(-1,1)

# Display standard error
print("se_OLS_m2 = ",se_m2.round(4))
print(var_m2.diagonal().round(4), betahat_m2)


se_OLS_m2 =  [[0.2591]
 [0.0194]
 [0.027 ]
 [0.0021]]
[0.0671 0.0004 0.0007 0.    ] [1.30695638 0.21995186 0.19476742 0.017803  ]


In [552]:
# Collecting results
results = {
    'Model 1': betahat_m1.round(4),
    'Model 2': betahat_m2.round(4),
    'Model 3': betahat_m3.round(4),
    'Model 4': betahat_m4.round(4)
}

# Create a list of coefficients names for the models
coef_names = ['Constant', "Dad's Education", "Mom's Education", 'Family Income', 'Number of Siblings', 'Nuclear Family', 'Urban', 'South']

# Constructing the LaTeX table
latex_table = """
\\begin{table}[H]
    \\centering
    \\begin{tabular}{lcccc}
        \\hline
        & Model 1 & Model 2 & Model 3 & Model 4 \\\\
        \\hline
"""
for i, coef in enumerate(coef_names):
    latex_table += "        {} & {} & {} & {} & {} \\\\\n".format(
        coef,
        results['Model 1'][i] if i < len(results['Model 1']) else '',
        results['Model 2'][i] if i < len(results['Model 2']) else '',
        results['Model 3'][i] if i < len(results['Model 3']) else '',
        results['Model 4'][i] if i < len(results['Model 4']) else ''
    )
latex_table += """        \\hline
    \\end{tabular}
    \\caption{OLS Estimation Results}
    \\label{tab:ols_results}
\\end{table}
"""

print(latex_table)


\begin{table}[H]
    \centering
    \begin{tabular}{lcccc}
        \hline
        & Model 1 & Model 2 & Model 3 & Model 4 \\
        \hline
        Constant & 1.15 & 1.307 & 2.116 & 2.1004 \\
        Dad's Education & 0.2565 & 0.22 & 0.2073 & 0.2073 \\
        Mom's Education & 0.2279 & 0.1948 & 0.1776 & 0.1683 \\
        Family Income &  & 0.0178 & 0.0173 & 0.0155 \\
        Number of Siblings &  &  & -0.1391 & -0.1454 \\
        Nuclear Family &  &  &  & 0.4312 \\
        Urban &  &  &  & -0.0496 \\
        South &  &  &  & -0.3478 \\
        \hline
    \end{tabular}
    \caption{OLS Estimation Results}
    \label{tab:ols_results}
\end{table}

