In [1]:
# magics: ensures that any changes to the modules loaded below will be re-loaded automatically
%load_ext autoreload
%autoreload 2
%load_ext line_profiler

# load general packages
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')

# load modules related to this exercise
from educationmodel_2 import EducationModel

In [10]:
model = EducationModel()

In [11]:
model.par.school_time_grid

array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
       19., 20.])

In [12]:
model.par.experience_grid

array([ 0.        ,  0.75327769,  1.52282226,  2.30985244,  3.11576017,
        3.94214896,  4.7908844 ,  5.66416187,  6.5645995 ,  7.49536946,
        8.46038933,  9.46461247, 10.5144914 , 11.61876587, 12.78992497,
       14.04727575, 15.42477032, 17.        ])

In [13]:
model.sol.V.shape

(3, 6, 15, 18, 5, 5, 5)

In [14]:
model.solve()

In [15]:
model.sol.d

array([[[[[[[0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.]],

           [[0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.]],

           [[0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.]],

           [[0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.]],

           [[0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.]]],


          [[[0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.],
  

In [20]:
model.sol.school_time.

(3, 15, 34, 6, 5, 5, 5)

In [19]:
model.sol.school_time[:,0,0,0,0,0]

(3, 15, 34, 6, 5, 5, 5)

In [9]:
# find average af sol.d 
model.sol.d.mean()


0.0

In [21]:
model.par.Nfix 

6